name: archive
version: 3.3.0
description: >-
  Provides encoders and decoders for various archive and compression formats
  such as zip, tar, bzip2, gzip, and zlib.
repository: https://github.com/brendan-duncan/archive
environment:
  sdk: ^3.5.0

dependencies:
  crypto: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  http:
  lints:
  test:
